import { getResource, queryResources } from './catalog'
import {
  createMockTask,
  decideMockGate,
  deleteMockTask,
  getMockTask,
  isMockTaskId,
  listMockTasks,
  subscribeMockTask,
  subscribeMockTasks,
} from '../data/mockPipeline'
import {
  addProjectResource,
  buildDiscoveryHandoff,
  confirmScientificTen,
  createProject,
  deleteProjects,
  generateScientificFigures,
  generateScientificTen,
  getEvidenceBundle,
  getProject,
  getSelectedProjectId,
  listProjects,
  removeProjectResource,
  selectDiscoveryIdea,
  setScientificFigureLanguage,
  setSelectedProjectId,
  subscribeProductStore,
  updateDiscoveryDraft,
  updateDiscoveryStep,
  updateProject,
  updateScientificFigureCopy,
  updateScientificTenItem,
} from './store'
import type { FrontendDataSource } from './types'

// Contract placeholder only. The fixture source below never issues a network request.
export const FUTURE_CATALOG_API_BASE = '/api/v1/catalog' as const

export const frontendDataSource: FrontendDataSource = {
  listProjects,
  getProject,
  createProject,
  updateProject,
  deleteProjects,
  getSelectedProjectId,
  setSelectedProjectId,
  updateDiscoveryDraft,
  updateDiscoveryStep,
  selectDiscoveryIdea,
  generateScientificTen,
  generateScientificFigures,
  setScientificFigureLanguage,
  updateScientificFigureCopy,
  updateScientificTenItem,
  confirmScientificTen,
  queryResources,
  getResource,
  addProjectResource,
  removeProjectResource,
  getEvidenceBundle,
  buildDiscoveryHandoff,
  listDemoTasks: listMockTasks,
  getDemoTask: getMockTask,
  isDemoTaskId: isMockTaskId,
  createDemoTask: createMockTask,
  deleteDemoTask: deleteMockTask,
  decideDemoGate: decideMockGate,
  subscribeDemoTask: subscribeMockTask,
  subscribeDemoTasks: subscribeMockTasks,
  subscribe: subscribeProductStore,
}
